### ISSUE TITLE
自动修复换行符的插件报错

### ISSUE THREAD

**Issue by chuliu-hash** [cx2333-gt/GalTransl#75]
json中的换行符是'\\n'（两个\）,     linebreakSymbol: "\n"时不生效，linebreakSymbol: "\\n"时（两个\），报错：

\plugins\text_common_linebreakFix\text_common_linebreakFix.py", line 81, in after_dst_processed
    tran.post_zh.insert(insert_pos, self.lb_char)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'insert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProtectArea\tool\GalTransl-main\GalTransl\__main__.py", line 31, in worker
    run(run_galtransl(cfg, translator))
  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\ProtectArea\tool\GalTransl-main\GalTransl\Runner.py", line 151, in run_galtransl
    await doLLMTranslate(
  File "D:\ProtectArea\tool\GalTransl-main\GalTransl\Frontend\GPT.py", line 230, in doLLMTranslate
    await gather(*tasks)  # run
    ^^^^^^^^^^^^^^^^^^^^
  File "D:\ProtectArea\tool\GalTransl-main\GalTransl\Frontend\GPT.py", line 152, in doLLMTranslateSingleFile
    LOGGER.error(f"插件 {plugin.name} 执行失败: {e}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value

**Comment by cx2333-gt** [comment]
感谢反馈。那是个还未完成的插件，不小心带到了release里
